/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.kmizu.compiler_interpreter

fun main(args: Array<String>) {
    when {
        args.size == 2 && args[0] == "-i" -> {
            val input = args[1]
            val tree: Ast = Parser.parse(input)
            val value: Int = Interpreter.interpret(tree)
            println(value)
        }
        args.size == 2 && args[0] == "-c" -> {
            val input = args[1]
            val tree: Ast = Parser.parse(input)
            Compiler.compileToFile(tree, "Main")
        }
        args.size == 2 && args[0] == "-r" -> {
            val input = args[1]
            val tree: Ast = Parser.parse(input)
            Compiler.compileAndRun(tree, "Main")
        }
    }
}
